// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vynmcwwgtrcyudjwdhgz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5bm1jd3dndHJjeXVkandkaGd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg5NDc0MDUsImV4cCI6MjA4NDUyMzQwNX0.Ly03tgGp58VM4blVelhilQYBn4CTyA7zsbujuRUvRBw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
